name: Automatic Tests
on:
  schedule:
    - cron: '30 10 * * *'
    - cron: '28 10 * * *'
  workflow_dispatch:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node16.16.0-chrome105-ff104-edge
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip
        run: |
          currentTime=`date +'%m%d%H%M%S'`
          echo ${currentTime}.zip
          echo "currentTime=${currentTime}" >> $GITHUB_ENV

      - name: Send to artifactory
        run: |
          echo "srm-${currentTime}.zip"