name: Automatic Tests
on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          install: npm install
          build: npm run test
